[project]
name = "macpy"
version = "0.1.0"
dependencies = [
    "rich",
]

[project.scripts]
macpy = "macpy.manage:main"

[tool.setuptools.packages.find]
where = ["."]
exclude = ["build*", "dist*", ".venv*", ".tox*"]